### ISSUE TITLE
Use multiple telegram accounts

### ISSUE THREAD

**Issue by Denys7814** [AliCl0ner/NotPixel#1]
Your code doesn't allow you to use multiple telegram accounts? Because how do you add multiple proxies?

**Comment by Denys7814** [comment]
<img width="580" alt="1" src="https://github.com/user-attachments/assets/9e5abef2-c4b5-4498-8c2c-673cc9c492d4">

I even recreated a new session in your bot, but it still hits 0 pixels((

**Comment by AliCl0ner** [comment]
you can turn off X3 in config.py. this is not a problem it check some pixel and their color for x3 point. If the color is not the main color then it will paint it so you get more point.
I see a None type error i will fix that
