### ISSUE TITLE
Plz fix this error

### ISSUE THREAD

**Issue by mezba74** [AliCl0ner/NotPixel#2]
Plz fix this error 
![Screenshot_2024-10-15-14-46-43-77_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/ce344576-d1b3-40ca-9709-de
![Screenshot_2024-10-15-14-46-43-77_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/c4b4f453-a3ac-437e-b609-4fdb29b4bdf1)
c2de6bb80f)

**Comment by mezba74** [comment]
After successful paint point increasing 0
![Screenshot_2024-10-15-14-50-23-87_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/131a7060-94e7-4165-b66e-94a4eec6131f)

Then code showing error

**Comment by AliCl0ner** [comment]
i fixed some of them. but it seems the no increase in balance is notpixel problem not the script. i did it manually but my balance didnt update
